- name: add php apt
  apt_repository:
    repo: ppa:ondrej/php
    state: present
- name: install php
  apt:
    name: "{{item}}"
    state: present
  loop:
    - software-properties-common
    - php{{php_version}}
    - php{{php_version}}-fpm
    - php{{php_version}}-pdo
    - php{{php_version}}-mysqlnd
    - php{{php_version}}-opcache
    - php{{php_version}}-xml
    - php{{php_version}}-gd
    - php{{php_version}}-dev
    - php{{php_version}}-mysql
    - php{{php_version}}-intl
    - php{{php_version}}-mbstring
    - php{{php_version}}-bcmath
    - php{{php_version}}-json
    - php{{php_version}}-iconv
    - php{{php_version}}-soap
- name: config php
  template:
    dest: "/etc/php/{{php_version}}/{{item}}/php.ini"
    src: "../templates/php.j2"
  loop:
    - cli
    - fpm
- name: restart php service
  service:
    name: "php{{php_version}}-fpm"
    state: restarted